name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    -
      name: Bump version and tag
      id: bumpandtag
      uses: anothrNick/github-tag-action@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
    -
      name: Write Version to File
      uses: brettdorrans/write-version-to-file@master
      with:
        filename: "version"
        placeholder: "$(major).$(minor).$(path)"
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - 
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
          images:
            ${{ secrets.DOCKER_HUB_USERNAME }}/communityconnections
          tags: |
            type=raw,value=latest
            type=semver,pattern={{ version }}
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/communityconnections:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/communityconnections:${{ steps.bumpandtag.outputs.tag }}

